/**
 * The types for importing an image — `import gb from "flag-icons/flags/4x3/gb.svg"`.
 *
 * Next writes these into `next-env.d.ts`, which is generated by a build and is not in git. So
 * `tsc --noEmit` only knew about them on a machine that had already built once — which is every
 * machine a person works on, and no machine in CI, where verify.sh runs typecheck before build.
 * CI had been failing on eleven flag SVGs since they were added; nobody saw it because the
 * billing block was answering every run in two seconds before it got that far.
 *
 * Referencing Next's own declarations rather than writing `declare module "*.svg"` here: a second
 * declaration with a different type would collide with theirs the moment a build does run.
 */
/// <reference types="next/image-types/global" />
